import fs from 'node:fs';
import path from 'node:path';
import { getProjectConfig } from './project-config.js';

export function computeAugmentation(outPath: string, servicesPath: string): string {
  let rel = path.relative(path.dirname(outPath), servicesPath).replace(/\\/g, '/');
  rel = rel.replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/, '');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return (
    `// devtooie-env.d.ts — generated by devtooie. Do not edit.\n` +
    // `export {}` makes this file a module, so the `declare module` below is a module
    // AUGMENTATION (merges `Register` into the real package) rather than an ambient module
    // declaration — which would shadow 'devtooie' and hide its real exports (defineAppConfigs, …).
    `export {};\n` +
    `declare module 'devtooie' {\n` +
    `  interface Register { appConfigs: typeof import('${rel}').default }\n` +
    `}\n`
  );
}

export function runTypegen(opts: { out?: string; cwd?: string } = {}): void {
  const cwd = opts.cwd ?? process.cwd();
  const cfg = getProjectConfig(cwd);
  if (!cfg) return; // nothing to generate without a project config
  const outPath = path.resolve(cwd, opts.out ?? 'devtooie-env.d.ts');
  const servicesPath = path.resolve(cwd, cfg.services);
  fs.writeFileSync(outPath, computeAugmentation(outPath, servicesPath));
}
