name: pr

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      SKIP_SIMPLE_GIT_HOOKS: 1
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.9.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm test

      - run: pnpm build
